### ISSUE TITLE
Remove contamination

### ISSUE THREAD

**Issue by mbhall88** [mbhall88/tbpore#1]
As we are trying to keep a low memory footprint and want to be able to distribute as many resources as possible with tbpore, we only really need to use the H37Rv reference and maybe a few other NTMs as well. Then we keep anything that maps to H37Rv.

Some NTM references can be found in https://www.nature.com/articles/srep45258#Sec25 and https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0214088

The code I used to do this in the head to head was https://github.com/mbhall88/head_to_head_pipeline/blob/3ed818c9f3754612a33060428ee651cd0f91234b/data/QC/Snakefile#L272-L383 (ignore the rule for extracting illumina reads obviously)

**Comment by iqbal-lab** [comment]
@leandro  - this is an active choice to definitely leave the human reference out

**Comment by leandro** [comment]
@iqbal-lab I guess you mentioned the wrong Leandro?

**Comment by leandro** [comment]
@iqbal-lab No worries! This is not the first time it happens (due to the simplicity of my username) and I'm pretty sure it won't be the last either. :)

**Comment by leoisl** [comment]
No decontamination step needed anymore

**Comment by leoisl** [comment]
Reopening for v`0.2`

**Comment by leoisl** [comment]
Closing in favour of https://github.com/mbhall88/tbpore/issues/21 to reduce noise
