### ISSUE TITLE
Output directory param or output consensus param?

### ISSUE THREAD

**Issue by leoisl** [mbhall88/tbpore#10]
We have an output directory parameter right now in `tbpore`:
```
@click.option(
    "-o",
    "--outdir",
    help="Directory to place output files",
    default=".",
    show_default=True,
    type=click.Path(file_okay=False, writable=True, path_type=Path),
)
```

However, the only output we are producing right now is a single consensus fasta file. Could we change this output directory parameter to an output consensus file, or are there other files we should be outputting and I am missing?

**Comment by iqbal-lab** [comment]
Mykrobe output and vcf file, right?

**Comment by mbhall88** [comment]
> Mykrobe output and vcf file, right?

Correct. Also, if someone uses the `--no-cleanup` option it should keep every file generated. This will be very valuable when/if we need to debug for the people in Madagascar (and anyone else using this tool).

**Comment by leoisl** [comment]
Just to confirm, `mykrobe` output is the `<sample>.mykrobe.json` file right? And the VCF file is the filtered SNPs VCF file that we apply to `H37RV` to get the consensus?

**Comment by iqbal-lab** [comment]
correct
