### ISSUE TITLE
Cryptic Mac OS CI issue

### ISSUE THREAD

**Issue by leoisl** [mbhall88/tbpore#12]
Haven't searched much, but don't know how to solve [this cryptic Mac OS CI issue](https://github.com/mbhall88/tbpore/runs/6130690527?check_suite_focus=true#step:4:88):
```
  ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/usr/local/miniconda/envs/tbpore/lib/python3.8/site-packages/~ackaging-20.9.dist-info'
```

This is happening when `poetry` is installing `toml`

**Comment by mbhall88** [comment]
I have a sneaking suspicion it might be related to https://github.com/python-poetry/poetry/issues/3336. I've also just updated the lock file (2db43e05b2bf76cedef11ec4a8c2915b67621016) as this *might* also be related.

**Comment by leoisl** [comment]
https://github.com/python-poetry/poetry/issues/3336 fixed the issue, thanks (see https://github.com/mbhall88/tbpore/pull/8/commits/c544976acc5823b5efebf6abce4fbb943bb45727)! [All builds now work](https://github.com/mbhall88/tbpore/actions/runs/2225598683). Updating the lock file has no effect for me, as the lock file is already updated in my fork:
```
(tbpore) leandro@leandro-ThinkPad-X1-Carbon-6th:~/git/tbpore$ poetry update
Updating dependencies
Resolving dependencies... (1.9s)

No dependencies to install or update
```

However, I had to create this [dev branch](https://github.com/mbhall88/tbpore/tree/dev) and change the base branch of the PR from `main` to `dev` because [the latest commit to the main branch](https://github.com/mbhall88/tbpore/commit/2db43e05b2bf76cedef11ec4a8c2915b67621016) creates a conflict with the PR, which causes github actions to not trigger CI. Now that this issue is solved, could we revert the latest commit on your `main` branch so I can merge again to it?

**Comment by mbhall88** [comment]
> Now that this issue is solved, could we revert the latest commit on your main branch so I can merge again to it?

Done in 1fdfa2b183f298dd3950272e7f1e0721c9690170
