### ISSUE TITLE
Add sample example

### ISSUE THREAD

**Issue by leoisl** [mbhall88/tbpore#14]
Should we add a sample example (a real but downsampled `fastq.gz` file), that could go potentially in the integration tests, and as a first test command for users to run? I am in doubt as this would make the package heavier

**Comment by mbhall88** [comment]
You could have the example just download a fastq from the ENA?

**Comment by leoisl** [comment]
Do you have a recommended fastq?

**Comment by leoisl** [comment]
Used `mada_1-7` from https://figshare.com/articles/dataset/samplesheet_csv/19304648 (see https://github.com/leoisl/tbpore/commit/4ec3089bf771712e0594bf660ba8d6f414dcc3c7)

**Comment by mbhall88** [comment]
Fine by me!
