### ISSUE TITLE
Run mykrobe

### ISSUE THREAD

**Issue by mbhall88** [mbhall88/tbpore#2]
This should use the settings used in the head to head paper. These will be released in mykrobe v0.11.0 (currently on master as `--ont`). If needing to set manually, the settings can found in https://github.com/mbhall88/head_to_head_pipeline/blob/master/analysis/resistance_prediction/workflow/rules/mykrobe.smk.

It is up for debate whether we want to use the `-A` option to report all calls. Maybe we can have this as an option in tbpore and have it turned off by default?

**Comment by leoisl** [comment]
Closed via https://github.com/mbhall88/tbpore/pull/8
