### ISSUE TITLE
Comparing `H2H` and `tbpore` output step by step

### ISSUE THREAD

**Issue by leoisl** [mbhall88/tbpore#23]
From https://github.com/leoisl/tbpore/commit/8a644c66857627e42fd3b81c08f87950b77ef74b , we have NTM+human decontamination in `tbpore`, so the results should be very similar to `H2H`, [however they are not](https://github.com/mbhall88/tbpore/issues/16#issuecomment-1121386506). https://github.com/mbhall88/tbpore/issues/16 is too long/convoluted, so I am starting this new issue to compare `H2H` and `tbpore` output step by step

**Comment by leoisl** [comment]
First step is comparing the set of decontaminated reads, which is done with [this script](https://github.com/leoisl/tbpore/blob/decontamination/pipelines/snakemake/scripts/compare_kept_reads.py). We are directly comparing the reads that should be kept after decontamination, skipping comparing the inner steps' outputs (index decontamination DB, map raw reads to DB, sort SAM, index BAM, run filter script on BAM).

Both decontamination steps differ by 57 reads per sample on average, with a max of 373 reads (sample `mada_1-33`), and a total of 5198 different reads:
```
Differences:
mada_1-19 15
mada_1-8 56
mada_1-6 140
mada_103 3
mada_1-1 18
mada_130 8
mada_132 5
mada_128 0
mada_2-1 8
mada_1-51 15
mada_1-20 23
mada_2-31 0
mada_109 52
mada_112 5
mada_1-5 92
mada_107 14
mada_1-40 14
mada_111 102
mada_1-14 39
mada_1-46 9
mada_136 109
mada_1-54 62
mada_1-25 12
mada_118 16
mada_129 1
mada_1-18 19
mada_151 24
mada_134 124
mada_1-3 184
mada_1-44 33
mada_1-15 2
mada_1-47 54
mada_2-53 8
mada_1-16 18
mada_1-2 253
mada_154 86
mada_104 3
mada_115 0
mada_126 1
mada_1-33 373
mada_102 22
mada_127 80
mada_125 2
mada_1-43 167
mada_137 49
mada_117 12
mada_131 5
mada_2-46 10
mada_1-17 136
mada_124 4
mada_121 132
mada_141 142
mada_2-42 4
mada_1-28 24
mada_152 193
mada_1-48 186
mada_2-34 254
mada_123 0
mada_106 6
mada_140 6
mada_1-30 8
mada_1-50 1
mada_139 1
mada_1-41 6
mada_2-25 20
mada_105 0
mada_144 107
mada_1-32 24
mada_1-22 74
mada_1-11 114
mada_1-10 59
mada_110 6
mada_120 1
mada_113 37
mada_1-38 38
mada_122 16
mada_1-7 17
mada_116 9
mada_142 144
mada_133 103
mada_148 139
mada_1-13 229
mada_1-53 0
mada_135 12
mada_1-12 60
mada_2-50 70
mada_1-21 5
mada_1-39 67
mada_1-36 22
mada_143 278
mada_150 97
Total 5198

```

**Comment by leoisl** [comment]
Now I will go into the inner steps of the decontamination pipeline to try to understand better why we are getting this difference in the decontaminated reads. The first step is to create a `minimap2` index of the  decontamination DB. This step creates a binary, proprietary `.mmi` file that is different between `H2H` and `tbpore`. There is an unavoidable difference between both tools here: `H2H` creates the index using `-I 12G` as it can afford to get a 12-GB machine in the cluster. `tbpore` has to be memory frugal, so we use `-I 500M` to get ~5GB max RAM usage. Remembering what this parameter is about in `minimap2:`
```
-I NUM       split index for every ~NUM input bases [4G]
```

So, I don't think there is nothing we can do about this step. `H2H` and `tbpore` will necessarily create different indexes, and we can't change `tbpore`, although we could change `H2H`. It is not possible to diff the indexes and understand the differences, so we go to the next step, with a hope that `minimap2` creates the same mapping for two indexes built with this flag differently.

Next step is mapping the raw reads to the decontamination DB index we just built. I am gathering some general stats about the `bam` file we create in this step for a single sample (`mada_1-33`, the one with 373 difference in reads in the decontamination step in the previous post), and showing that this mapping is not exact between `H2H` and `tbpore` with different `minimap2` versions, although is similar:

`H2H`:
```
$ samtools flagstat /hps/nobackup/iqbal/mbhall/tech_wars/data/QC/mapped/madagascar/mada_1-33.nanopore.sorted.bam
2210351 + 0 in total (QC-passed reads + QC-failed reads)
433338 + 0 secondary
326976 + 0 supplementary
2169669 + 0 mapped (98.16% : N/A)
1409355 + 0 primary mapped (97.19% : N/A)
```

`tbpore with minimap 2.24`:
```
$ samtools flagstat /hps/nobackup/iqbal/leandro/tbpore2/tbpore/pipelines/snakemake/output_human_decon/mada_1-33/.tbpore/mada_1-33.decontaminated.sorted.bam
2204836 + 0 in total (QC-passed reads + QC-failed reads)
427829 + 0 secondary
326970 + 0 supplementary
2163909 + 0 mapped (98.14% : N/A)
1409110 + 0 primary mapped (97.18% : N/A)
```

`tbpore with minimap 2.22`:
```
$ samtools flagstat /hps/nobackup/iqbal/leandro/tbpore2/tbpore/pipelines/snakemake/output_human_decon_mada_1-33_minimap2_2.22/mada_1-33/.tbpore/mada_1-33.decontaminated.sorted.bam
2204684 + 0 in total (QC-passed reads + QC-failed reads)
427803 + 0 secondary
326844 + 0 supplementary
2163758 + 0 mapped (98.14% : N/A)
1409111 + 0 primary mapped (97.18% : N/A)
```

`tbpore with minimap2 2.17`:
```
$ samtools flagstat /hps/nobackup/iqbal/leandro/tbpore2/tbpore/pipelines/snakemake/output_human_decon_mada_1-33_minimap2_2.17/mada_1-33/.tbpore/mada_1-33.decontaminated.sorted.bam
2205537 + 0 in total (QC-passed reads + QC-failed reads)
427832 + 0 secondary
327668 + 0 supplementary
2164797 + 0 mapped (98.15% : N/A)
1409297 + 0 primary mapped (97.19% : N/A)
```

(this version actually increased significantly the difference in decontaminated reads: from 373 to 673)

# Conclusion

`H2H` and `tbpore` have differences when they map the raw ONT reads to the decontamination DB. It is not trivial to replicate the exact `minimap2` version used in `H2H`, as `minimap2 2.17` was used to build the DB, but `minimap2 2.22` was used to run the mappings (see https://github.com/mbhall88/tbpore/issues/16#issuecomment-1122252168). We have differences in mapping when comparing `H2H` to `tbpore` with 3 different versions of `minimap2`: 2.24, 2.22 and 2.17. I think we should rerun the whole `H2H` pipeline to fix these issues of tool versioning - only with this we will be sure that all files were generated by the same version of the tools and all results are updated, as we are doing an exact comparison here, not an inexact one, so I have to be sure that everything was generated using the latest pipeline state if I want to understand the differences. Or we accept having these differences and compare the clusters we get with `H2H` and `tbpore`...

**Comment by leoisl** [comment]
# Minimap2 creates slightly different mappings depending on the index size

### Version
```
$ minimap2 --version
2.24-r1122
```

### Building indexes

Large `-I`, index is not split:
```
minimap2 -I 30G  -x map-ont -t 1 -d decon_DB_no_splitting   /hps/nobackup/iqbal/leandro/tbpore2/tbpore/data/decontamination_db/remove_contam.fa.gz 
```

Small `-I` (what we use in `tbpore`), index is split:
```
minimap2 -I 500M -x map-ont -t 1 -d decon_DB_with_splitting /hps/nobackup/iqbal/leandro/tbpore2/tbpore/data/decontamination_db/remove_contam.fa.gz 
```

### Mapping same reads to both indexes
```
minimap2                       -aL2 -x map-ont -t 1 -o decon_DB_no_splitting.sam   decon_DB_no_splitting   ../mada_1-33.fq.gz
minimap2 --split-prefix prefix -aL2 -x map-ont -t 1 -o decon_DB_with_splitting.sam decon_DB_with_splitting ../mada_1-33.fq.gz
```

### Checking mapping stats

No splitting:
```
$ samtools flagstat decon_DB_no_splitting.sam
2210489 + 0 in total (QC-passed reads + QC-failed reads)
1450037 + 0 primary
433362 + 0 secondary
327090 + 0 supplementary
0 + 0 duplicates
0 + 0 primary duplicates
2169807 + 0 mapped (98.16% : N/A)
1409355 + 0 primary mapped (97.19% : N/A)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (N/A : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (N/A : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)
```

With splitting:
```
$ samtools flagstat decon_DB_with_splitting.sam 
2204836 + 0 in total (QC-passed reads + QC-failed reads)
1450037 + 0 primary
427829 + 0 secondary
326970 + 0 supplementary
0 + 0 duplicates
0 + 0 primary duplicates
2163909 + 0 mapped (98.14% : N/A)
1409110 + 0 primary mapped (97.18% : N/A)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (N/A : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (N/A : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)
```

The important bit is the primary mapping:
No splitting, is exactly what we got in the `H2H`:
```
1409355 + 0 primary mapped (97.19% : N/A)
```

Which differs  with splitting:
```
1409110 + 0 primary mapped (97.18% : N/A)
```

# Conclusion

`minimap2` creates slightly different mappings depending on the index size. This explains all the difference we saw in the previous post.

**Comment by iqbal-lab** [comment]
I vote option 2, to check the universe is not mad, and then look at final results

**Comment by mbhall88** [comment]
Hasn't Leandro already proven option 2? But as Zam said, if you want to make sure the universe isn't mad go option 2 then 3 I guess.
