### ISSUE TITLE
Check md5sum or sha256 of decontamination DB index to ensure we have the correct index

### ISSUE THREAD

**Issue by leoisl** [mbhall88/tbpore#27]
Just noticed this when making PR https://github.com/mbhall88/tbpore/pull/26 . This will impact a little bit runtime, as the DB index is 9GB, but I think is worth it to make sure we are using the correct index...

**Comment by iqbal-lab** [comment]
surely dont need to do it every time you run. once on download enough?

**Comment by iqbal-lab** [comment]
we don't sha all our fastq and PRGs every time we run pandora?

**Comment by leoisl** [comment]
Yeah, was just being fancy :( . Will add the sha-256 sums to the FTP so that they can ensure they have downloaded the index fine
