### ISSUE TITLE
Run several samples at once

### ISSUE THREAD

**Issue by leoisl** [mbhall88/tbpore#37]
This is a request from Floriane and Pedro from our meeting on 18/05/2022.

Their samples come in batches, so it would be helpful if `tbpore process` could be run on several samples with a single command instead of having to run a `tbpore process` command per sample.

**Comment by mbhall88** [comment]
That does complicate things a bit taking multiple samples as tbpore accepts multiple input files and directories, so I can't think of a way of delineating samples.

Is there anything wrong with a plain old bash `for` loop?

**Comment by charneglanz** [comment]
The following worked well for me to run samples in parallel:

ls /path/to/fastqs/ | grep fastq.gz | sed 's/.fastq.gz//' > samples_parallel.txt

cat samples_parallel.txt | parallel --bar -j 2 tbpore process -o /path/to/output/ -A /path/to/fastqs/{}.fastq.gz 

An important thing to note here is to use the default option of no clean-up. If you specify clean-up to be performed all temporary files will be removed when the analysis of a single sample is finished, including temporary files created for the analysis of other samples. Those other samples will therefore not be able to progress in the pipeline.

Hope this helps :)

**Comment by leoisl** [comment]
Thanks @charneglanz ! I do think there is no need to implement this feature, `parallel` seems to do the job! I do note however that allowing cleanup of the `tbpore` temp files might be an important option for the parallel runs. @mbhall88 I think easiest and good solution would be to create a subdirectory inside the temp directory to be the temp dir for each sample. Do you agree or do you propose an alternative solution?

**Comment by mbhall88** [comment]
> @mbhall88 I think easiest and good solution would be to create a subdirectory inside the temp directory to be the temp dir for each sample. Do you agree or do you propose an alternative solution?

That sounds like a good idea
