### ISSUE TITLE
Align reads to H37Rv

### ISSUE THREAD

**Issue by mbhall88** [mbhall88/tbpore#4]
Align the subsampled, decontaminated reads (#3) to H37Rv - this will be used for variant calling. 

https://github.com/mbhall88/head_to_head_pipeline/blob/3ed818c9f3754612a33060428ee651cd0f91234b/analysis/baseline_variants/Snakefile#L111-L134 is how I did this in the paper.

**Comment by leoisl** [comment]
Closed via https://github.com/mbhall88/tbpore/pull/8
