### ISSUE TITLE
Comparing paper results with results with new filters (min_depth 5, min_qual 25, min_mq 30)

### ISSUE THREAD

**Issue by leoisl** [mbhall88/tbpore#40]
This issue is to compare paper results with results obtained with new filters. These new filters are `min_depth 5` (paper is `0`), `min_qual 25` (paper is `85`), `min_mq 30` (paper is `0`). It is worth noting that some filters were left untouched, i.e. `min_fed 0.2`, `min_strand_bias 1`, `min_vdb 0.00001` and `min_frs 0.90`. This is related to https://github.com/mbhall88/tbpore/issues/22 but there will be several plots comparison here, so I am starting a new issue.

**Comment by leoisl** [comment]
# Transmission clusterings

Summary: this has been shown and discussed previously, it is added here just for completeness. New filters improve `SACP` and `XCR` for both nanopore threshold, at the cost of decreasing `SACR` for the higher nanopore threshold.

## Paper

![image](https://user-images.githubusercontent.com/8397967/171177584-1eb939af-0920-444b-8f21-8ea584dafab5.png)

## New results

![image](https://user-images.githubusercontent.com/8397967/171177646-85268a95-6654-4477-9054-7fb0a75f12ed.png)

**Comment by leoisl** [comment]
# Full Pairwise SNP distance 

Summary: In general, with the new filters we have points closer to the identity line, with the majority of points over the identity line, which is expected as nanopore has more errors than illumina.

## Paper

![image](https://user-images.githubusercontent.com/8397967/171185623-243926ef-c665-4276-89b2-fdff46167be7.png)

## New filters

![image](https://user-images.githubusercontent.com/8397967/171185672-ce58af84-6179-4c27-a663-add895942880.png)

**Comment by leoisl** [comment]
# Mixed modality self-distance

Summary: Very similar results

## Paper

![image](https://user-images.githubusercontent.com/8397967/171189422-4773965d-4121-42bf-a867-20fbcc09c126.png)


## New filters

![image](https://user-images.githubusercontent.com/8397967/171189448-5a08f7b5-b4aa-4ad7-b078-a846b55be23a.png)

**Comment by mbhall88** [comment]
Hmmm, this is really interesting!! Thanks a lot Leandro. The full dotplot is great!

I am very tempted to go with these new filters, but my only reservation is the increase in clustering FNs. In the paper, one of our main arguments is that nanopore does not miss any isolates from their true (Illumina) cluster. Given these FNs are at the 5-SNP threshold. and not the 12 - which is a more lenient threshold exactly for this reason - it is tempting to take the hit...

Let's wait and see what @iqbal-lab thinks when he is back.

**Comment by iqbal-lab** [comment]
I think this is amazing.  How about go with new results as default. In terms of the paper, how do you like this @mbhall88 

1. In response to reviewers explain clearly why we switched 
2. In the paper main section say we tuned to get better snp distance correlation,  precision. Small cost in recall at the second snp threshold,  but we provide in supp info a second set of filters which optimises for recall.

**Comment by mbhall88** [comment]
That sounds perfect

**Comment by leoisl** [comment]
I think this can be closed?

**Comment by mbhall88** [comment]
Ah shit. Just realised these new params never made it into the default params for tbpore

**Comment by mbhall88** [comment]
Sorted in v0.4.0
