### ISSUE TITLE
Subsampled meaning

### ISSUE THREAD

**Issue by jloubser** [mbhall88/tbpore#49]
Hi there,

What does the ''subsampled" mean in the vcf filenames?

**Comment by mbhall88** [comment]
It just means the VCF was obtained from subsampled reads. I can understand this seems confusing. I'll look into changing that.

**Comment by jloubser** [comment]
sorry to comment on this again...is there a way to 'disable' rasusa and not do the subsampling from the fastq file?

**Comment by mbhall88** [comment]
@jloubser see #53. I'll try get around to it this week.
