### ISSUE TITLE
Call SNPs with bcftools

### ISSUE THREAD

**Issue by mbhall88** [mbhall88/tbpore#5]
Using `mpileup` and `call`. **MUST** be bcftools version `>=1.13`. (Nothing of relevance to these subcommands seems to have changed in the recent versions so probably safe to use any version above 1.13)

https://github.com/mbhall88/head_to_head_pipeline/blob/3ed818c9f3754612a33060428ee651cd0f91234b/analysis/baseline_variants/Snakefile#L137-L180

**Comment by iqbal-lab** [comment]
fwiw, my paranoia would prefer pinning a version, and only changing versions after testing performance. @mbhall88 
saw so many changes with versions during his project

**Comment by mbhall88** [comment]
Sure. The big change happened from 1.12 to 1.13. But pinning to 1.13 is smart I guess.

**Comment by leoisl** [comment]
Closed via https://github.com/mbhall88/tbpore/pull/8
