### ISSUE TITLE
TBpore fails while running rasusa

### ISSUE THREAD

**Issue by ycode-sh** [mbhall88/tbpore#56]
I am trying to use tbpore on some data sets for the first time. I have installed the software, the database and other dependencies (both using conda and pypi). However the pipeline fails whenever it gets to running rasusa. 

`Started running rasusa -c 150 -g 4411532 -s 88 -o One_RESULT/.tbpore/sample_116.subsampled.fastq.gz -i One_RESULT/.tbpore/sample_116.sorted.fastq.gz ...
[2024-06-09 08:52:00] ERROR    | Error calling rasusa -c 150 -g 4411532 -s 88 -o One_RESULT/.tbpore/sample_116.subsampled.fastq.gz -i One_RESULT/.tbpore/sample_116.sorted.fastq.gz (return code 2)`

The error log file returns
`error: unexpected argument '-c' found`

I'd appreciate your assistance in helping to troubleshoot the error

**Comment by iqbal-lab** [comment]
Cc @mbhall88

**Comment by mbhall88** [comment]
Ah this is probably due to my recent major version change for rasusa. Can you confirm what version of rasusa you're running? `rasusa --version`

**Comment by ycode-sh** [comment]
Thank you very much for this. TBPORE is now working well.

I suspect something is wrong with conda installation. The tbpore version
installed via conda is 0.1.0. I had to install using pip to get tbpore to
function well. Please help check this

**Comment by mbhall88** [comment]
Are you trying to install the conda package into a new environment?

i.e. if you do `conda create -n tbpore tbpore=0.7.1` do you get issues?

**Comment by ycode-sh** [comment]
Thank you very much. The download works perfectly with conda create -n
tbpore tbpore=0.7.1.

But when i tried running the analysis again, using the new conda
environment, I got this error:

ERROR    | Error calling minimap2 -aL2 -x map-ont -t 6 -o
RESULTS/.tbpore/sample_116.decontaminated.sam
/home/dfgmrtc/.tbpore/decontamination_db/remove_contam.map-ont.mmi
RESULTS/.tbpore/sample_116.fq.gz (return code -9)


Installation with pip (following manual installation of dependencies) works
very fine. No errors. I think the conda installation should be checked
again for possible bugs

**Comment by mbhall88** [comment]
Return code -9 generally means the process was killed as it ran out of memory. How much memory does your computer have?

I ran the latest tbpore with a sample and it all worked fine. But do note the peak memory is around 12-13GB (from loading the database) and given the minimap2 command was returned in the error it appears this was the command that hit the memory limit.

**Comment by ycode-sh** [comment]
You are correct. The problem was memory-related and has been resolved.
Thank you for responding promptly to my questions. Thank you again
