### ISSUE TITLE
Filter SNPs

### ISSUE THREAD

**Issue by mbhall88** [mbhall88/tbpore#6]
This is the pipeline code to run the script https://github.com/mbhall88/head_to_head_pipeline/blob/3ed818c9f3754612a33060428ee651cd0f91234b/analysis/baseline_variants/Snakefile#L183-L228

And this is the script https://github.com/mbhall88/head_to_head_pipeline/blob/master/analysis/baseline_variants/scripts/apply_filters.py

**Comment by leoisl** [comment]
Closed via https://github.com/mbhall88/tbpore/pull/8
